version: "3"

services:

  scylla-node1:
    image: scylladb/scylla:4.1.0
    restart: always
    command: --seeds=scylla-node1,scylla-node2 --smp 1 --memory 750M --overprovisioned 1 --api-address 0.0.0.0
    volumes:
      - "./scylla/scylla.yaml:/etc/scylla/scylla.yaml"
      - "./scylla/cassandra-rackdc.properties.dc1.r1:/etc/scylla/cassandra-rackdc.properties"
      - "./scylla/create_ks_db.cql:/create_ks_db.cql"
      - "./scylla/run_inserts.sh:/run_inserts.sh"
      - "./scylla/cassandra_LCS_profile.yaml:/cassandra_LCS_profile.yaml"
      - "./scylla/cassandra_STCS_profile.yaml:/cassandra_STCS_profile.yaml"
      - "./scylla/cassandra_TWCS_profile.yaml:/cassandra_TWCS_profile.yaml"
    networks:
      web:

  scylla-node2:
    image: scylladb/scylla:4.1.0
    restart: always
    command: --seeds=scylla-node1,scylla-node2 --smp 1 --memory 750M --overprovisioned 1 --api-address 0.0.0.0
    volumes:
      - "./scylla/scylla.yaml:/etc/scylla/scylla.yaml"
      - "./scylla/cassandra-rackdc.properties.dc1.r2:/etc/scylla/cassandra-rackdc.properties"
    networks:
      web:

  scylla-node3:
    image: scylladb/scylla:4.1.0
    restart: always
    command: --seeds=scylla-node1,scylla-node2 --smp 1 --memory 750M --overprovisioned 1 --api-address 0.0.0.0
    volumes:
      - "./scylla/scylla.yaml:/etc/scylla/scylla.yaml"
      - "./scylla/cassandra-rackdc.properties.dc1.r3:/etc/scylla/cassandra-rackdc.properties"
    networks:
      web:

networks:
  web:
    driver: bridge
